### ISSUE TITLE
Отсутсвует файл "руководство для участников" и "лицензия"

### ISSUE THREAD

**Issue by EPoY74** [vndv/querynomicon#13]
Здравствуйте!

При проверке и  попытке прочитать как пнервое, так и второе, вышла ошибка 404

![image](https://github.com/user-attachments/assets/470db544-9084-4825-9f39-6bfbfe0f81e0)
![image](https://github.com/user-attachments/assets/4f6a810f-e30d-43d1-a1ef-30f59cd760b4)

Спасибо за продукт! Буду помогать :))))

**Comment by vndv** [comment]
Привет!
На оригинальном сайте при переходе на эти ссылки так же 404
Со своей стороны это пофиксить не можем.
https://lessonomicon.github.io/querynomicon/

**Comment by rozhnev** [comment]
Может добавим свои? Лицензию и руководство для участников?

https://lessonomicon.github.io/querynomicon/license.html

https://lessonomicon.github.io/querynomicon/contributing.html
