### ISSUE TITLE
Remove paragraph "Полное внешнее соединение"

### ISSUE THREAD

**Issue by rozhnev** [vndv/querynomicon#32]
SQLite does not support FULL OUTER JOIN, so I advice to remove this paragraph or move it to advanced module. 
Currently we can create some unpublished file and move into it such issues before we'll decide about them.

**Comment by vndv** [comment]
I think we can use this [example](https://www.sql-easy.com/learn/sqlite-full-outer-join/) with `union` to realize full outer join

**Comment by rozhnev** [comment]
SQLite version updated, so it works now
