### ISSUE TITLE
Translate schema to Russian 

### ISSUE THREAD

**Issue by rozhnev** [vndv/querynomicon#69]
https://querynomic.one/#/resources/introduction?id=%d0%9f%d0%be%d0%b4%d0%ba%d0%bb%d1%8e%d1%87%d0%b5%d0%bd%d0%b8%d0%b5-%d0%ba-%d0%b1%d0%b0%d0%b7%d0%b5-%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d1%85

The above schema (on picture) texts should be translated to Russian. The result prefer be an SVG image.

**Comment by rozhnev** [comment]
https://draw.io/ tool can be used for schema creation and export to SVG

**Comment by vndv** [comment]
Done!
